### ISSUE TITLE
Компонент для Yii2

### ISSUE THREAD

**Issue by G1K** [perf2k2/direct#1]
Доброго времени суток, заметил что вы так же занимаетесь Yii2.
Планируется компонент коннектор для модуля Яндекс Директ Api v5

**Comment by perf2k2** [comment]
Доброго! Планируется, но не раньше августа - сентября, к этому времени как раз рассчитываю выкатить стабильную версию модуля.

**Comment by perf2k2** [comment]
Не актуально
