### ISSUE TITLE
Независимость от env

### ISSUE THREAD

**Issue by G1K** [perf2k2/direct#2]
Использование жестко прошитых в env доступов сильно мешает.
Когда у тебя не один токен доступа.

Перенесите пожалуйста инициализацию при создании сервиса.

**Comment by perf2k2** [comment]
При отправке запроса можно указывать инстанс соденинения, которое его отправляет, при этом каждому соединению можно указать отдельный env файл. Например так:

```
        $response = Ads::archive()
            ->setSelectionCriteria(
                (new IdsCriteria())
                    ->setIds([])
            )
            ->createAndSendRequest(new Connection($configDir, $isSandbox, $configFile));

        $response2 = Ads::archive()
            ->setSelectionCriteria(
                (new IdsCriteria())
                    ->setIds([])
            )
            ->createAndSendRequest(new Connection($configDir, $isSandbox, $configFile2));
```
Таким образом можно работать сразу с несколькими соедниениями. Это не решает проблему?

**Comment by G1K** [comment]
Частично решает, но не очень удобно плодить конфигурационные файлы к примеру когда токен один, а аккаунтов несколько.
Такое бывает например когда используем токен представителя агенства который имеет доступы к нескольким разным клиентам, а в API директа нужно передавать именно логин клиента.

Удобнее реализация в соседней библиотеке, поэтому пока использую ее, но ваша библиотечка тоже приглянулась, возможно позже перейду )

```
$token = YOUR_TOKEN;
$login = CLIENT_LOGIN;

$client = new DirectApiService($token, $login);

$campaigns = $client
    ->getCampaignsService()
    ->get(
        new CampaignsSelectionCriteria(
            [   
                'States' => [
                    CampaignStateEnum::ON
                ]   
            ]   
        ),  
        CampaignFieldEnum::getValues()
    ); 
```

**Comment by perf2k2** [comment]
Ок) О таком варианте использования (несколько логинов на токен) не задумывался честно говоря, постараюсь учесть.
